[package]
name = "call-trace-macro"
version = "0.1.0"
authors = ["Marvin Löbel <loebel.marvin@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15", features = ["full"]}
quote = "0.6"
